version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb+srv://kumarvinayak829:qJGqZkVDPcRAYhHs@vehicledata.gskjh.mongodb.net/?retryWrites=true&w=majority&appName=VehicleData

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"